#!/var/jb/bin/sh
launchctl unload /var/jb/Library/LaunchDaemons/com.supremeinspirit.hipcharge.plist 2>/dev/null
launchctl load /var/jb/Library/LaunchDaemons/com.supremeinspirit.hipcharge.plist
exit 0
